# Errors
Date: 2025-10-24 14:00

## Github CI Pipeline

### Build Docker Immage

- *Test Docker Image*

```
##[debug]Evaluating condition for step: 'Test Docker image'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Test Docker image
##[debug]Loading inputs
##[debug]Loading env
Run docker run --rm aetherlens/home:test python --version
##[debug]/usr/bin/bash -e /home/runner/work/_temp/4a714fb1-674f-4603-a3ba-4d9b90876aa4.sh
Unable to find image 'aetherlens/home:test' locally
docker: Error response from daemon: pull access denied for aetherlens/home, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Run 'docker run --help' for more information
Error: Process completed with exit code 125.
##[debug]Finishing: Test Docker image
```
